apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gmo-ingestor
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: marketdata
  project: default
  source:
    repoURL: https://github.com/Shion1305/gmocoin-data-lab.git
    targetRevision: HEAD
    path: deploy/k8s/ingestor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
